version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: my_wiremock
    volumes:
      - ./wiremock/_files:/home/wiremock/_files
      - ./wiremock/_mappings:/home/wiremock/mappings
    ports:
      - 8443:8080
